"""Generates aotr_texmem_gen.inc: one placeholder method per vtable slot of the four interfaces the memory textures
(aotr_texmem.inc) stand in for - IDirect3DDevice9, IDirect3D9, IDirect3DTexture9, IDirect3DSurface9. A placeholder
notes that it was called (interface, slot) and fails with E_NOTIMPL while cleaning up the right number of stdcall
arguments; aotr_texmem.inc overwrites the slots D3DX really uses with working methods. The device's argument counts
come from the same table gen_rt_hooks.py generates the render thread's hooks from."""
import os, re

here = os.path.dirname(os.path.abspath(__file__))
src = open(os.path.join(here, "gen_rt_hooks.py"), encoding="utf-8").read()
tables = src[src.index("DEV = ["):src.index("def tokens")]
ns = {}
exec(tables, ns)

def nargs(spec):
    n = 0; i = 0
    while i < len(spec):
        c = spec[i]
        if c in "vohs":
            n += 1; i += 1
        elif c == "p":
            j = i + 1
            if spec[j] == "c":
                k = j + 1
                while spec[k].isdigit(): k += 1
                i = k + 2
            else:
                k = j
                while k < len(spec) and spec[k].isdigit(): k += 1
                i = k
            n += 1
        else:
            raise ValueError(spec)
    return n

D3D = [("QueryInterface", 2), ("AddRef", 0), ("Release", 0), ("RegisterSoftwareDevice", 1), ("GetAdapterCount", 0),
       ("GetAdapterIdentifier", 3), ("GetAdapterModeCount", 2), ("EnumAdapterModes", 4), ("GetAdapterDisplayMode", 2),
       ("CheckDeviceType", 5), ("CheckDeviceFormat", 6), ("CheckDeviceMultiSampleType", 6), ("CheckDepthStencilMatch", 5),
       ("CheckDeviceFormatConversion", 4), ("GetDeviceCaps", 3), ("GetAdapterMonitor", 1), ("CreateDevice", 6)]
classes = [("dev", [(n, nargs(a)) for n, a, k in ns["DEV"]]), ("d3d", D3D),
           ("tex", [(n, nargs(a)) for n, a, k in ns["TEX"]]), ("surf", [(n, nargs(a)) for n, a, k in ns["SURF"]])]
assert len(classes[0][1]) == 119 and len(classes[2][1]) == 22 and len(classes[3][1]) == 17

out = ["// GENERATED by gen_texmem_stubs.py - do not edit by hand."]
for ci, (cls, slots) in enumerate(classes):
    for s, (name, n) in enumerate(slots):
        params = "void*" + "".join(", DWORD" for _ in range(n))
        out.append("static DWORD __stdcall txs_%s_%d(%s) { txUnimpl(%d, %d); return 0x80004001u; }   // %s" % (cls, s, params, ci, s, name))
    out.append("static void* g_txVt_%s[%d] = { %s };" % (cls, len(slots), ", ".join("(void*)&txs_%s_%d" % (cls, s) for s in range(len(slots)))))
    out.append("static const char* const kTxName_%s[%d] = { %s };" % (cls, len(slots), ", ".join('"%s"' % n for n, _ in slots)))
open(os.path.join(here, "aotr_texmem_gen.inc"), "w", encoding="utf-8", newline="\n").write("\n".join(out) + "\n")
print("aotr_texmem_gen.inc: %d placeholder methods" % sum(len(s) for _, s in classes))
