"""Generates gd_funcs.inc: sorted start addresses of game.dat functions, for in-process profile attribution.
Sources: direct call targets, code that follows int3 alignment padding, and .rdata pointers into .text whose
preceding byte is padding or a return (vtable entries). Input: the capstone linear sweep text_sweep.tsv
(address<TAB>mnemonic<TAB>operands) and game.dat itself."""
import os, struct, sys

GAME = r"C:\AgeoftheRing\rotwk\game.dat"
SWEEP = sys.argv[1] if len(sys.argv) > 1 else "text_sweep.tsv"
d = open(GAME, "rb").read()
pe = struct.unpack_from("<I", d, 0x3C)[0]
nsec = struct.unpack_from("<H", d, pe + 6)[0]; optsz = struct.unpack_from("<H", d, pe + 20)[0]
base = struct.unpack_from("<I", d, pe + 24 + 28)[0]
secs = []
p = pe + 24 + optsz
for i in range(nsec):
    nm = d[p:p + 8].rstrip(b"\0").decode("latin1"); vs, va, rs, ro = struct.unpack_from("<IIII", d, p + 8)
    secs.append((nm, va, max(vs, rs), ro, rs)); p += 40
text = [s for s in secs if s[0] == ".text"][0]
tlo, thi = base + text[1], base + text[1] + text[2]
def byte_at(va):
    for nm, sva, sz, ro, rs in secs:
        if sva <= va - base < sva + rs: return d[ro + va - base - sva]
    return None

starts = set()
prev_mn = None
insn_prev = {}                                          # instruction start -> previous instruction's mnemonic
for line in open(SWEEP):
    a, mn, op = line.rstrip("\n").split("\t")
    addr = int(a, 16)
    insn_prev[addr] = prev_mn
    if mn == "call" and op.startswith("0x"):
        try:
            t = int(op, 16)
            if tlo <= t < thi: starts.add(t)
        except ValueError:
            pass
    if prev_mn == "int3" and mn != "int3":
        starts.add(addr)
    prev_mn = mn
rdata = [s for s in secs if s[0] == ".rdata"]
for nm, sva, sz, ro, rs in rdata:
    blob = d[ro:ro + rs]
    for off in range(0, len(blob) - 3, 4):
        v = struct.unpack_from("<I", blob, off)[0]
        if tlo < v < thi and insn_prev.get(v) in ("int3", "ret", "jmp", "nop"):
            starts.add(v)
starts = sorted(starts)
out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "gd_funcs.inc")
with open(out, "w", newline="\n") as f:
    f.write("// GENERATED by gen_game_funcs.py - start addresses of game.dat functions (profile attribution only)\n")
    f.write("static const DWORD kGameFuncs[%d] = {\n" % len(starts))
    for i in range(0, len(starts), 12):
        f.write("  " + ",".join("0x%06X" % s for s in starts[i:i + 12]) + ",\n")
    f.write("};\nstatic const int kGameFuncCount = %d;\n" % len(starts))
print("wrote %s: %d function starts" % (out, len(starts)))
